### ISSUE TITLE
Examples / Docs

### ISSUE THREAD

**Issue by NOP0** [slowtec/modbus-core#2]
Hi, I'm not sure about the relation between this crate and the tokio crate. 

I'm interested in using this crate because of the no_std, but it is a bit though to get going without docs or examples. But then again maybe this crate is not meant for standalone use?

Thanks! :smile:

**Comment by flosse** [comment]
> Hi, I'm not sure about the relation between this crate and the tokio crate.

In the long term the `modbus-core` will be used as base for `tokio-modbus`.

> I'm interested in using this crate because of the no_std,

What target platform do you use?

> but it is a bit though to get going without docs or examples.

What example would you like to see? A modbus server implementation?  Or a client example?

> But then again maybe this crate is not meant for standalone use?

It's definitely meant as a standalone crate for embedded systems :)

**Comment by NOP0** [comment]
Hi, target platform is STM32 boards or micro:bit (hobbyist use).

The examples in the modbus tokio repo are nice!

**Comment by flosse** [comment]
> Hi, target platform is STM32 boards or micro:bit (hobbyist use).

STM32 should work. I have no experiences with micro:bit yet.

> The examples in the modbus tokio repo are nice!

Instead of guessing what you need I'd suggest that you push your current code somewhere so that we can help you out.

**Comment by NOP0** [comment]
Hi, it was decided to go for a Linux-capable platform for the prototype, so then we will be using the tokio crate. Thanks

**Comment by 4egod** [comment]
Hi. Could you please provide some examples for modbus tcp client (Modbus Master)? Thank you in advance!
